# ============================
# CI/CD PIPELINE (Drone)
# Pattern: Host-git + Compose
# ============================
# What this does:
# 1) Sync the repo into the runner host at /opt/repo/<repo_name>  (persistent)
# 2) Build a Docker image from this repo and push it to GHCR
# 3) Deploy using the host's docker-compose.yml in /opt/repo/<repo_name>
#
# PREREQS (Ops):
# - Drone runner mounts:
#     - /var/run/docker.sock   (so steps can talk to host Docker)
#     - /opt/repo              (where we keep deploy copies)
# - Secrets set in Drone repo settings:
#     GHCR_USERNAME = <github username or org>
#     GHCR_TOKEN    = <PAT with read:packages, write:packages, repo>

kind: pipeline
type: docker
name: build_and_deploy

trigger:
  event: [push, custom]
  branch: [main]

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: repo_root
    host:
      path: /opt/repo

steps:
  # 1) Sync the repo into the host folder: /opt/repo/<repo_name_lowercase>
  - name: sync-host-repo
    image: alpine:3.20
    volumes:
      - name: repo_root
        path: /opt/repo
    environment:
      REPO_DIR: "/opt/repo/${DRONE_REPO_NAME,,}"
    commands:
      - apk add --no-cache git
      - REMOTE_URL="$(git -C $DRONE_WORKSPACE config --get remote.origin.url)"
      - mkdir -p "$REPO_DIR"
      - echo "Starting repo sync to $REPO_DIR..."
      - >
        if [ ! -d "$REPO_DIR/.git" ]; then
          echo "Cloning repository...";
          git clone --depth=1 --progress "$REMOTE_URL" "$REPO_DIR";
        else
          echo "Updating existing repository...";
          git -C "$REPO_DIR" remote set-url origin "$REMOTE_URL" || true;
          git -C "$REPO_DIR" fetch --all --prune --progress;
          git -C "$REPO_DIR" reset --hard "origin/${DRONE_BRANCH}";
        fi
      - echo "Checking out commit ${DRONE_COMMIT_SHA}..."
      - git -C "$REPO_DIR" checkout -f "${DRONE_COMMIT_SHA}" || true
      - echo "Repository sync complete!"
      - ls -lah "$REPO_DIR"

  # 2) Build & push backend image to GHCR
  - name: build-push-backend
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: ghcr.io
      repo: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN

  # 2b) Build & push frontend image to GHCR
  - name: build-push-frontend
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: ghcr.io
      repo: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}-frontend
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.frontend
      context: .
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN

  # 3) Deploy using the host compose file
  - name: deploy
    image: docker:27-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: repo_root
        path: /opt/repo
    environment:
      REPO_DIR: "/opt/repo/${DRONE_REPO_NAME,,}"
      GHCR_USERNAME:
        from_secret: GHCR_USERNAME
      GHCR_TOKEN:
        from_secret: GHCR_TOKEN
      TAG: "latest"
      REPO_NAME: "${DRONE_REPO_NAME,,}"
      COMPOSE_SUBDIR: ""
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - export TAG="latest"
      - export GHCR_USERNAME=$(echo "$GHCR_USERNAME" | tr '[:upper:]' '[:lower:]')
      - export REPO_NAME="${DRONE_REPO_NAME,,}"
      - cd "$REPO_DIR${COMPOSE_SUBDIR:+/}${COMPOSE_SUBDIR}"
      - docker compose pull
      - docker compose up -d
